### ISSUE TITLE
Verify minimum functionality on application before 2nd week presentation.

### ISSUE THREAD

**Issue by ashleye37** [J-Lindley/Intervue#19]

**Comment by ItsLahRee** [comment]
WEEK #2: 

A functioning minimal viable product (i.e., a prototype version of your app that shows the intended function). This should be as close to a working app as possible and include:

A 5-7 minute presentation that discusses what your app is, what it does, and how it works. You will be presented to instructors and TAs during class.
 
OUR APP: InterVue

WHAT YOUR APP IS:  Place to find technical interview questions organized by language, that lets the user take notes and save questions to study

WHAT YOUR APP DOES: Populates Language-Specific Technical Interview Questions for New Developers

HOW IT WORKS: 

A screenshot of your Project Management Board that shows a breakdown of tasks assigned to group members with a schedule. This should be updated to reflect the remaining priorities and completed tasks.

UPDATED PROJECT BOARD:

**Comment by ItsLahRee** [comment]
WEEK #2: 

A functioning minimal viable product (i.e., a prototype version of your app that shows the intended function). This should be as close to a working app as possible and include:

A 5-7 minute presentation that discusses what your app is, what it does, and how it works. You will be presenting to instructors and TAs during class.

WHAT YOUR APP IS:  

WHAT YOUR APP DOES: 

HOW IT WORKS: 

A screenshot of your Project Management Board that shows breakdown of tasks assigned to group members with a schedule. This should be updated to reflect remaining priorities and completed tasks.

UPDATED PROJECT BOARD:

**Comment by ashleye37** [comment]
We were able to verify that our backend is working fairly well. Need to continue working on getting the backend wired up to front end but the app does route correctly and pull data from our database.
