### ISSUE TITLE
Decide on color scheme and fonts for App.

### ISSUE THREAD

**Issue by ashleye37** [J-Lindley/Intervue#7]

**Comment by ItsLahRee** [comment]
I'm thinking our focus is on simplicity for this application. Our main motivation is to help simplify searching for interview questions. A sans-serif font would add an aesthetic presence of our mission.  Today I'll be looking into capturing a simple clean font to use.

**Comment by ItsLahRee** [comment]
<img width="910" alt="Screen Shot 2019-07-23 at 8 28 14 PM" src="https://user-images.githubusercontent.com/45607966/61763074-eb848980-ad88-11e9-82e5-ea95efd9b3f4.png">

**Comment by ItsLahRee** [comment]
<img width="911" alt="Screen Shot 2019-07-23 at 8 30 53 PM" src="https://user-images.githubusercontent.com/45607966/61763101-022ae080-ad89-11e9-9564-5b9de2beccb6.png">

**Comment by ItsLahRee** [comment]
"Aller" Font Choice #1
ABCDEFGHIJKLM
NOPQRSTUVWXYZ
abcdefghijklm
nopqrstuvwxyz
1234567890

**Comment by ItsLahRee** [comment]
Potential Icon: 
<img width="438" alt="Screen Shot 2019-07-23 at 8 39 21 PM" src="https://user-images.githubusercontent.com/45607966/61763399-1cb18980-ad8a-11e9-8bf1-280d0d056f21.png">

**Comment by ItsLahRee** [comment]
Font Pair Option
<img width="513" alt="Screen Shot 2019-07-23 at 8 48 54 PM" src="https://user-images.githubusercontent.com/45607966/61763760-664ea400-ad8b-11e9-9008-5bf28ac9fd72.png">

**Comment by ItsLahRee** [comment]
Font Pair Option #2 
<img width="519" alt="Screen Shot 2019-07-23 at 8 51 45 PM" src="https://user-images.githubusercontent.com/45607966/61763837-bd547900-ad8b-11e9-930d-9237ff6ebf40.png">
